name: LaTeX Compilation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: thesis.tex
          working_directory: thesis
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Upload Compiled Thesis
        uses: actions/upload-artifact@v2
        with:
          name: Full Text PDF
          path: thesis/thesis.pdf
