name: Compile Final Presentation
on:
  push:
    branches: [ master ]
    paths: [ 'presentations/final/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'presentations/final/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: presentation.tex
          working_directory: presentations/final
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Upload Compiled Document
        uses: actions/upload-artifact@v2
        with:
          name: Final Presentation PDF
          path: presentations/final/presentation.pdf
